from typing import Dict, List, Optional
from collections import defaultdict

def create_inverse_groups(groups:Dict[str, Optional[str]]) -> Dict[str, List[str]]:
    inverse_groups = defaultdict(lambda: list())

    for action, group in groups.items():
        inverse_groups[group].append(action)

    return inverse_groups

groups = defaultdict(lambda: None, {
    'heat':'heat',
    'cook':'heat',
    'bake':'heat',
    'grill':'heat',
    'melt':'heat',
    'blend':None,
    'beat':'prepare',
    'spread':None,
    'cool':'cool',
    'brown':'heat',
    'cut':'prepare',
    'chill':'cool',
    'drain':None,
    'boil':'heat',
    'simmer':'heat',
    'pour':None,
    'freeze':'cool',
    'saute':'heat',
    'rinse':'prepare',
    'warm':'heat',
    'wash':'prepare',
    'knead':'prepare',
    'peel':'prepare',
    'parboil':'heat',
    'break':'prepare',
    'broil':'heat',
    'scorch':'heat',
    'skim':None,
    'fry':'heat',
    'refrigerate':'cool',
    'burn':'heat',
    'thicken':None,
    'grate':'prepare',
    'brush':'prepare',
    'open':'prepare',
    'crack':'prepare',
    'poach':'heat',
    'slice':'prepare',
    'whisk':None,
    'dice':'prepare',
    'marinate':None,
    'whip':None,
    'sour':None,
    'soak':None,
    'steam':'heat',
    'chop':'prepare',
    'mince':None,
    'mash':'prepare',
    'squeeze':'prepare',
    'wipe':'prepare',
    'thaw':'prepare',
    'curdle':'heat',
    'sweeten':None,
    'baste':None,
    'carve':None,
    'grind':'prepare',
    'debone':'prepare',
    'steep':None,
    'clarify':None,
    'macerate':'prepare',
    'crumple':'prepare',
    'braise':'heat',
    'gut':None,
    'bury':None,
    'place':None,
    ## additional verbs
    'stir': 'mix',
    'blend in': None,
    'remove': None,
    'spoon into': 'mix',
    'drop': None,
    'sprinkle': 'season',
    'preheat': 'heat',
    'sift': None,
    'add': 'mix',
    'add in': 'mix',
    'put': 'mix',
    'mix': 'mix',
    'cover': None,
    'uncover': None,
    'leave to cool': 'cool',
    'grease': 'prepare',
    'flour': 'prepare',
    'divide': 'prepare',
    'roll': 'prepare',
    'spoon': None,
    'lay': None,
    'layer': None,
    'coat': 'heat',
    'beat together': 'prepare',
    'combine': 'mix',
    'form': 'prepare',
    'frost': 'cool',
    'fill': 'prepare',
    'filling': 'prepare',
    'season': 'season',
    'shred': 'prepare',
    'whisk together': 'mix',
    'stir in': 'mix',
    'let cool': 'cool',
    'make': 'prepare',
    'top': 'season',
    'sprinkle over': 'season',
    'cut off': 'prepare',
    'shape': 'prepare',
    'spread over': None,
    'chop up': 'prepare',
    'toast': 'heat',
    'toss': 'mix',
    'toss in': 'mix',
    'pour over': None,
    'oil': 'prepare',
    'stuff': 'prepare',
    'cut up': 'prepare',
    'prepare': 'prepare',
    'mix in': 'mix',
    'marinade': 'season',
    'heat through': 'heat',
    'warm through': 'heat',
    'mixing': 'mix',
    'pour in': 'mix',
    'top off': 'season',
    'whisk in': 'mix',
    'microwave': 'heat',
    'toss together': 'mix',
    'cut in': 'prepare',
    'crush': 'prepare',
    'decorate': None,
    'roast': 'heat',
    'process': 'prepare',
    'salt': 'season',
    'bake in': 'heat',
    'cooking': 'heat',
    'butter': 'prepare',
    'cook stir': 'heat',
    'cutting': 'prepare',
    'refrigerate': 'cool',
    'whisking': None,
    'blend together': 'mix',
    'trim': 'prepare'
})

inverse_groups = create_inverse_groups(groups)
